services:
  postgres:
    image: postgres:16
    container_name: carmarket_postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: carmarket

    ports:
      - "5432:5432"

    volumes:
      - "postgres_data:/var/lib/postgresql/data"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d carmarket"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    container_name: carmarket_backend

    ports:
      - "8000:8000"

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/carmarket
      SECRET_KEY: ab98a7ba8029c21147b98c2cddcb22e2820e3925e306f1fa0c44e7f884519552

    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build: ./frontend/carmarket
    container_name: carmarket_frontend

    ports:
      - "4200:80"

    depends_on:
      - backend

volumes:
  postgres_data:
