"""add indexes on brand, year, price

Revision ID: 5204b0456c7b
Revises: a308330f5da6
Create Date: 2026-07-21 04:03:17.337913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5204b0456c7b'
down_revision: Union[str, Sequence[str], None] = 'a308330f5da6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_car_listings_brand'), 'car_listings', ['brand'], unique=False)
    op.create_index(op.f('ix_car_listings_price'), 'car_listings', ['price'], unique=False)
    op.create_index(op.f('ix_car_listings_year'), 'car_listings', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_car_listings_year'), table_name='car_listings')
    op.drop_index(op.f('ix_car_listings_price'), table_name='car_listings')
    op.drop_index(op.f('ix_car_listings_brand'), table_name='car_listings')
    # ### end Alembic commands ###
