"""add user_id fk to car_listings

Revision ID: a308330f5da6
Revises: 0afb3885ad3c
Create Date: 2026-07-14 19:42:10.167895

"""

import uuid
from typing import Sequence, Union
from datetime import datetime, timezone

from alembic import op
import sqlalchemy as sa

from app.core.security import hash_password

# revision identifiers, used by Alembic.
revision: str = "a308330f5da6"
down_revision: Union[str, Sequence[str], None] = "0afb3885ad3c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("car_listings", sa.Column("user_id", sa.String(), nullable=True))
    op.create_foreign_key(
        "fk_car_listings_user_id",
        "car_listings",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
    users_table = sa.table(
        "users",
        sa.column("id", sa.String),
        sa.column("username", sa.String),
        sa.column("email", sa.String),
        sa.column("hashed_password", sa.String),
        sa.column("created_at", sa.DateTime(timezone=True)),
    )

    admin_id = str(uuid.uuid4())
    op.bulk_insert(
        users_table,
        [
            {
                "id": admin_id,
                "username": "admin_user",
                "email": "adminuser@example.com",
                "hashed_password": hash_password("adminpassword"),
                "created_at": datetime.now(timezone.utc),
            }
        ],
    )

    car_listings_table = sa.table("car_listings", sa.column("user_id", sa.String))
    op.execute(
        car_listings_table.update()
        .where(car_listings_table.c.user_id.is_(None))
        .values(user_id=admin_id)
    )

    op.alter_column("car_listings", "user_id", nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_car_listings_user_id", "car_listings", type_="foreignkey")
    op.drop_column("car_listings", "user_id")
    # ### end Alembic commands ###
